name: Benchmark on self-hosted runners

on:
  pull_request:
    types: [opened,edited,synchronize,labeled]

env:
  SYCL_BENCH_BENCHMARKS: 2DConvolution 2mm 3DConvolution 3mm DRAM arith atax atomic_reduction bicg correlation covariance fdtd2d gemm gesummv gramschmidt host_device_bandwidth kmeans lin_reg_coeff lin_reg_error local_mem matmulchain median mol_dyn mvt nbody pattern_L2 reduction scalar_prod segmentedreduction sf syr2k syrk usm_accessors_latency usm_allocation_latency usm_instr_mix usm_pinned_overhead vec_add

jobs:
  run-sycl-bench:
    if: contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.pull_request.labels.*.name, 'benchmark-sycl-bench')
    runs-on: [self-hosted, gpu-nvidia]
    permissions: write-all
    strategy:
      matrix:
        clang_version: ['15']
        cuda: ['11.0']
    steps:
    - uses: actions/checkout@v4
    - name: Build AdaptiveCpp
      run: |
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${{matrix.clang_version}} -DCLANG_EXECUTABLE_PATH=/usr/bin/clang++-${{matrix.clang_version}} -DLLVM_DIR=/usr/lib/llvm-${{matrix.clang_version}}/cmake -DWITH_CUDA_BACKEND=ON -DWITH_ROCM_BACKEND=Off -DWITH_OPENCL_BACKEND=Off -DCMAKE_INSTALL_PREFIX=`pwd`/install -DCUDA_TOOLKIT_ROOT_DIR=/opt/cuda-${{matrix.cuda}} ..
        make -j16 install
        cp /.singularity.d/libs/libcuda.* `pwd`/install/lib/
    - name: Build sycl-bench
      run: |
        git clone https://github.com/bcosenza/sycl-bench.git
        cd sycl-bench
        mkdir build && cd build
        cmake .. -DSYCL_IMPL=AdaptiveCpp -DAdaptiveCpp_DIR=${GITHUB_WORKSPACE}/build/install/lib/cmake/AdaptiveCpp/ -DACPP_TARGETS=generic
        make $SYCL_BENCH_BENCHMARKS
        
    - name: Run SYCL-Bench
      run: |
        cd sycl-bench/bin
        mkdir benchmarks
        for benchmark in $SYCL_BENCH_BENCHMARKS; do cp ../build/$benchmark ./benchmarks/$benchmark; done
        ./run-suite gpu-warmup
        python3 ${GITHUB_WORKSPACE}/devops/sycl-bench_to_json.py sycl-bench.csv sycl-bench.json
        cat sycl-bench.json
        mv sycl-bench.json ${GITHUB_WORKSPACE}

    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store new result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: SYCL-Bench benchmark
        tool: customSmallerIsBetter
        output-file-path: sycl-bench.json
        external-data-json-path: ./cache/sycl-bench-cache.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-on-alert: true
        summary-always: true
        comment-always: true


